/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 */

const sourceDir = './src'
const destinationDir = './build'
const projectURL = 'weave.test'

const mix = require('laravel-mix')
const tailwindcss = require('tailwindcss')
const purgecss = require('@fullhuman/postcss-purgecss')({
    content: [`${sourceDir}/**/*.{twig,js}`],
    defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || [],
    whitelist: ['html', 'body', 'pre', 'code', 'hr'],
    whitelistPatterns: [],
})
// const purgecss = require('@fullhuman/postcss-purgecss')({
//     content: [
//         `${viewsDir}/*`,
//         `${destinationScripts}/*`,
//     ],
//     extractors: [
//         {
//             extractor: class {
//                 static extract(content) {
//                     return content.match(/[A-Za-z0-9-_:/]+/g) || []
//                 }
//             },
//             // extensions: ['html', 'js', 'svg'],
//         },
//     ],
//     whitelist: [],
//     whitelistPatterns: [],
// })

// Disable notifications
mix.disableNotifications()

// JavaScript
mix.js(`${sourceDir}/js/app.js`, `${destinationDir}/js/app.js`)

// PostCSS
// https://github.com/postcss/postcss/blob/master/docs/plugins.md
mix.postCss(`${sourceDir}/css/style.css`, `${destinationDir}/css/style.css`, [
    require('postcss-import'),
    tailwindcss('./tailwind.config.js'),
    require('postcss-hexrgba'),
    require('postcss-nested'),
    require('postcss-calc'),
    ...(mix.inProduction()
        ? [
              purgecss,
              require('postcss-flexibility'),
              require('pixrem'),
              require('cssnano'),
          ]
        : []),
    require('autoprefixer'),
])

// Copy images
mix.copyDirectory(
    `${sourceDir}/assets/images`,
    `${destinationDir}/assets/images`
)

// BrowserSync
// https://browsersync.io/docs/options/
mix.browserSync({
    proxy: projectURL,
    files: [
        `${destinationDir}/**/*`,
        // `${sourceDir}/**/*.{twig,html}`,
        // `${imagesDir}/**/*.{png,jpg,jpeg,gif,webp,svg}`,
    ],
})

// Sourcemaps
if (!mix.inProduction()) {
    mix.sourceMaps()
}

// Options
mix.options({
    processCssUrls: false,
})

// Webpack config
mix.webpackConfig({
    devtool: !mix.inProduction() && 'source-map',
    module: {
        rules: [
            {
                test: /\.js$/,
                include: [path.resolve(__dirname, 'node_modules')],
            },
        ],
    },
})

// Full API
// mix.js(src, output);
// mix.react(src, output); <-- Identical to mix.js(), but registers React Babel compilation.
// mix.preact(src, output); <-- Identical to mix.js(), but registers Preact compilation.
// mix.coffee(src, output); <-- Identical to mix.js(), but registers CoffeeScript compilation.
// mix.ts(src, output); <-- TypeScript support. Requires tsconfig.json to exist in the same folder as webpack.mix.js
// mix.extract(vendorLibs);
// mix.sass(src, output);
// mix.less(src, output);
// mix.stylus(src, output);
// mix.postCss(src, output, [require('postcss-some-plugin')()]);
// mix.browserSync('my-site.test');
// mix.combine(files, destination);
// mix.babel(files, destination); <-- Identical to mix.combine(), but also includes Babel compilation.
// mix.copy(from, to);
// mix.copyDirectory(fromDir, toDir);
// mix.minify(file);
// mix.sourceMaps(); // Enable sourcemaps
// mix.version(); // Enable versioning.
// mix.disableNotifications();
// mix.setPublicPath('path/to/public');
// mix.setResourceRoot('prefix/for/resource/locators');
// mix.autoload({}); <-- Will be passed to Webpack's ProvidePlugin.
// mix.webpackConfig({}); <-- Override webpack.config.js, without editing the file directly.
// mix.babelConfig({}); <-- Merge extra Babel configuration (plugins, etc.) with Mix's default.
// mix.then(function () {}) <-- Will be triggered each time Webpack finishes building.
// mix.override(function (webpackConfig) {}) <-- Will be triggered once the webpack config object has been fully generated by Mix.
// mix.dump(); <-- Dump the generated webpack config object to the console.
// mix.extend(name, handler) <-- Extend Mix's API with your own components.
// mix.options({
//   extractVueStyles: false, // Extract .vue component styling to file, rather than inline.
//   globalVueStyles: file, // Variables file to be imported in every component.
//   processCssUrls: true, // Process/optimize relative stylesheet url()'s. Set to false, if you don't want them touched.
//   purifyCss: false, // Remove unused CSS selectors.
//   terser: {}, // Terser-specific options. https://github.com/webpack-contrib/terser-webpack-plugin#options
//   postCss: [] // Post-CSS options: https://github.com/postcss/postcss/blob/master/docs/plugins.md
// });
